name: "Tests"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    name: npm test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci

  integ:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - windows-latest
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

    #Test setup specific version
      - uses: ./
        with:
          file-path: "test/resources/env-file-1.env"
      - run: |
          echo "var1=$var1"
          echo "var2=$var2"
          echo "var3=$var3"
          echo "var4=$var4"
          echo "var5=$var5"
          echo "var6=$var6" 

      # Test setup default version
      - uses: ./
        with:
          file-path: "test/resources/env-file-2.env"
          delimiter: ':'
      - run: |
          echo "var1:$var1"
          echo "var2:$var2"
          echo "var3:$var3"
          echo "var4:$var4"
          echo "var5:$var5"
          echo "var6:$var6"
